language: go

script:
  - go get github.com/golang/dep/...
  - dep ensure
  - go test ./...



go:
- 1.x
# - 1.10.x
# - master
env:
  - VERSION=$(grep Version bot/version.go | cut -d'"' -f2 | tail -1) GOOS=linux GOARCH=amd64
before_deploy:
  - cp *.md bin/
  - GOOS=${GOOS} GOARCH=${GOARCH} go build -o bin/blurblurbot-${GOOS}-${GOARCH}-${VERSION} . && tar -C bin/ -czvf blurblurbot-${GOOS}-${GOARCH}-${VERSION}.tar.gz blurblurbot-${GOOS}-${GOARCH}-${VERSION} *.md
deploy:
  provider: releases
  file: blurblurbot-${GOOS}-${GOARCH}-${VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    # condition: $TRAVIS_GO_VERSION =~ ^1\.10\.[0-9]+$
  api_key:
    secure: jJ1HxNl2kNsmPiEub+GB2PEfQ28bgP93fvQJ7kgkPrFPHw962p6N+YuDQsdrJL4RUANLYJUpNSOBkZsd6LHnUhFKNDNTGULpbFAUq9T7yDO+de6c0hKZ4AwMhaieMKMYaxql7McLEeMR9oFWysNV8Uq+yEC+8cjKEGu0bWTfUrQDy8v95ErbRr8mWZadtXb34cgNU1/JBar6ZVw7VtVeG/VIJTv7ziLxz/As9uJbUsvKG8BNkSPHS9PnPxGTltVfDYvcdHuBNTs4Ynny29ZJNWU5hVK418lWyTlhMWu06naBI9p59PkOpssw5yOKzP90cJttfQvk3AeWXGmaNE7f6TRhnIHAsAMxOj1QGQq3/DXeUvRZQ+8U8UiAVd658zQuYWcZ/d4wFhMJMR2toijzce7NW/2L6VORDGzkEkJ+71mxLnnF7ex1CMzXEzJWeOaxbfxcuCRO0hO1H8U7l/MkKoZuajTdfFzfQGpnqa43M+UxeUwlrJrjD43+inyO4JpLdD11KSsIiuQUnwGshX7ot7mhxUYScwzrMzg5eyOb7XdiztrEgf4O9tffrMsAeue3C+GR5tHjmdlt4AesJSS/vzOQXszXFTwcEQ2GZmpnjWskqhDbF/2h1aCFMvVuTwaCIuyLTQzo9W7rJpJeeU0lDl94gWNTdsWuPI5J1S+OHio=
