FROM golang:alpine AS build-environment

RUN apk --no-cache add --virtual .build-deps curl git

RUN go get -u github.com/golang/dep/...

WORKDIR /go/src/github.com/dtchanpura/blurblurbot
COPY . /go/src/github.com/dtchanpura/blurblurbot

RUN dep ensure && CGO_ENABLED=0 go install github.com/dtchanpura/blurblurbot/...

FROM alpine:latest

COPY --from=build-environment /go/bin/blurblurbot /blurblurbot

RUN adduser -D blurblurbot

USER blurblurbot

ENTRYPOINT ["/blurblurbot"]

EXPOSE 8080
